-- Aucune migration en attente.
-- (La migration recipe_ingredients + recipes.steps a été appliquée le
-- 07/07/2026 au matin via le SQL Editor ; check:schema complet 11/11.
-- La grande migration du 06/07 — locations, sources, recipes, realisations,
-- events, event_recipes — avait été appliquée le 06/07/2026 au soir.)
